### ISSUE TITLE
No sound on the latest chromium based browser

### ISSUE THREAD

**Issue by tsekityam** [phateio/kiris#1]
I tried to listen on Chromium based browsers, such as Opera Developer v.38.0.2213.0 or Google Chrome Canary 64bit 52.0.2730.0, on Mac, however, all of them failed to play the music. I opened the console and saw this error, `Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.`, occurred again and again.

![screen shot 2016-05-11 at 10 05 52 am](https://cloud.githubusercontent.com/assets/3814422/15168029/295b43f6-1760-11e6-8c3b-ba2157646359.png)

**Comment by shikendon** [comment]
Hi @tsekityam,

Due to licensing reasons, Chromium does not have native support for MP3 Audio format. You can test your browser support through this site [Which audio formats are supported?](http://hpr.dogphilosophy.net/test/).

Here is some result of browsers on Mac:

- Google Chrome 50.0.2661.94 (64-bit)
![chrome_50 0 2661 94](https://cloud.githubusercontent.com/assets/1556383/15186819/24d977fa-17d1-11e6-95ce-aada6cb053bc.png)

- Chromium 51.0.2683.0 (64-bit)
![chromium_51 0 2683 0](https://cloud.githubusercontent.com/assets/1556383/15186821/24da4ee6-17d1-11e6-9b62-5745512e09d6.png)

- Firefox 46.0.1
![firefox_46 0 1](https://cloud.githubusercontent.com/assets/1556383/15186820/24d989de-17d1-11e6-80e8-3027d7f6f997.png)

- Safari 9.1 (11601.5.17.1)
![safari_9 1](https://cloud.githubusercontent.com/assets/1556383/15186822/24dd12de-17d1-11e6-90d3-5a9ee8c15063.png)

See also:
- [HTML5 Audio#Supported_audio_coding_formats](https://en.wikipedia.org/wiki/HTML5_Audio#Supported_audio_coding_formats)

We are also evaluate other formats like OGG, Weba and AAC. Maybe we will migrate our system to one of them someday when it is supported by major browsers. Thank you for your report.

**Comment by tsekityam** [comment]
Although Google Chrome Canary and Opera Developer are based on Chromium, however, they do have builtin MP3 support, so I don't think that it is a codec problem.
 

- Google Chrome Canary
![screen shot 2016-05-12 at 2 42 46 pm](https://cloud.githubusercontent.com/assets/3814422/15206201/e77b12c2-184f-11e6-97f9-b6335e9e301a.png)

- Opera Developer
![screen shot 2016-05-12 at 2 42 21 pm](https://cloud.githubusercontent.com/assets/3814422/15206202/e78279f4-184f-11e6-9550-5117ae7d0a91.png)

**Comment by shikendon** [comment]
After some investigation, it seems Chromium erroneously trigger the suspend event on audio in latest version. I have no idea is it a bug or feature. I comment out the suspend event temporary. It should be normal now. Thanks.

Audio Event Test: https://jsfiddle.net/shikendon/s0jvgwLx/

- Google Chrome 50.0
![chrome](https://cloud.githubusercontent.com/assets/1556383/15218722/beecfb24-1893-11e6-991f-d8d1cda135a9.png)

- Opera developer 39.0
![opera_developer_with_square](https://cloud.githubusercontent.com/assets/1556383/15218911/72cd038c-1894-11e6-95c6-4debcf61fff7.png)
